name: Pull Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: echo //registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN} > .npmrc
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Bootstrap
        run: npm ci

      - name: Lib Tests
        run: npx lerna run test

      - name: Build Integration (Own)
        run: npx tsc -p integration/own && npx vite build integration/own

      - name: Build Integration (Mixed)
        run: npx tsc -p integration/mixed && npx vite build integration/mixed
